

import {
  LayoutDashboard,
  Users,
  FileText,
  CheckSquare,
  Calendar as CalendarIcon,
  Settings,
  Plus,
  Search,
  MoreHorizontal,
  ChevronRight,
  BrainCircuit,
  Upload,
  Sparkles,
  Printer,
  X,
  Menu,
  FileEdit,
  User as UserIcon,
  HelpCircle,
  Copy,
  Check,
  Trash
} from 'lucide-react';

export const Icons = {
  Dashboard: LayoutDashboard,
  Clients: Users,
  Contracts: FileText,
  Tasks: CheckSquare,
  CheckSquare: CheckSquare,
  Calendar: CalendarIcon,
  Settings: Settings,
  Plus: Plus,
  Search: Search,
  More: MoreHorizontal,
  ChevronRight: ChevronRight,
  Brain: BrainCircuit,
  Upload: Upload,
  Sparkles: Sparkles,
  Print: Printer,
  Close: X,
  Menu: Menu,
  Edit: FileEdit,
  User: UserIcon,
  Help: HelpCircle,
  FileText,
  Copy,
  Check,
  Trash,
  Users
};