-- Seed Data

-- 1. Create Demo Tenant
INSERT INTO tenants (id, name, subdomain, plan)
VALUES 
    ('11111111-1111-1111-1111-111111111111', 'Estudio Jurídico Demo', 'demo', 'premium')
ON CONFLICT DO NOTHING;

-- 2. Create Users
-- Password hash for 'password123' (bcrypt/argon2 dependent, using placeholder for demo)
-- In a real scenario, these hashes must be generated by the app. 
-- For this seed, we assume the app handles login or these are for testing.
INSERT INTO users (id, tenant_id, email, password_hash, name, role, is_active)
VALUES
    ('22222222-2222-2222-2222-222222222222', '11111111-1111-1111-1111-111111111111', 'admin@demo.com', '$2b$10$X7.X7.X7.X7.X7.X7.X7.X7.X7.X7.X7.X7.X7.X7.X7', 'Admin User', 'super_admin', true),
    ('33333333-3333-3333-3333-333333333333', '11111111-1111-1111-1111-111111111111', 'abogado@demo.com', '$2b$10$X7.X7.X7.X7.X7.X7.X7.X7.X7.X7.X7.X7.X7.X7.X7', 'Dr. Abogado', 'lawyer', true),
    ('44444444-4444-4444-4444-444444444444', '11111111-1111-1111-1111-111111111111', 'paralegal@demo.com', '$2b$10$X7.X7.X7.X7.X7.X7.X7.X7.X7.X7.X7.X7.X7.X7.X7', 'Paralegal User', 'paralegal', true)
ON CONFLICT DO NOTHING;

-- 3. Create Contract Categories (Argentine Legal Context)
INSERT INTO contract_categories (tenant_id, name, description, is_judicial)
VALUES
    ('11111111-1111-1111-1111-111111111111', 'Juicios', 'Demandas, contestaciones, escritos judiciales', true),
    ('11111111-1111-1111-1111-111111111111', 'Derecho de Familia', 'Régimen de comunicación, cuidado personal', true),
    ('11111111-1111-1111-1111-111111111111', 'Divorcios', 'Divorcio unilateral, presentación conjunta', true),
    ('11111111-1111-1111-1111-111111111111', 'Alimentos', 'Reclamo de cuota alimentaria, ejecución', true),
    ('11111111-1111-1111-1111-111111111111', 'Sucesiones', 'Declaratoria de herederos, inicio de sucesión', true),
    ('11111111-1111-1111-1111-111111111111', 'Corporativo / Contratos', 'Contratos comerciales, estatutos', false),
    ('11111111-1111-1111-1111-111111111111', 'Laboral', 'Intercambio telegráfico, demandas laborales', true),
    ('11111111-1111-1111-1111-111111111111', 'Inmobiliario', 'Boleto de compraventa, alquileres', false)
ON CONFLICT DO NOTHING;

-- 4. Set Permissions
INSERT INTO permissions (tenant_id, role, can_view_all_documents, can_upload_documents, can_delete_documents, access_contract_generator, access_settings)
VALUES
    ('11111111-1111-1111-1111-111111111111', 'super_admin', true, true, true, true, true),
    ('11111111-1111-1111-1111-111111111111', 'lawyer', true, true, true, true, false),
    ('11111111-1111-1111-1111-111111111111', 'paralegal', true, true, false, false, false),
    ('11111111-1111-1111-1111-111111111111', 'assistant', false, true, false, false, false)
ON CONFLICT DO NOTHING;

